export const LOADING_POKEMONS = 'LOADING_POKEMONS';
export const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID';
export const SET_INDEX_PAGE = 'SET_INDEX_PAGE';
export const SET_SEARCH_QUERY='SET_SEARCH_QUERY';
export const FILTER_POKEMONS_BY_NAME='FILTER_POKEMONS_BY_NAME';
export const RESET_POKEMONS='RESET_POKEMONS';